CREATE DATABASE IF NOT EXISTS nodejs_base1;
USE nodejs_base1;

CREATE TABLE users(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(180) NOT NULL UNIQUE,
    name VARCHAR(90) NOT NULL,
    lastname VARCHAR(90) NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    image VARCHAR(255) NULL,
    password VARCHAR(150) NOT NULL,
    created_at TIMESTAMP(0) NOT NULL,
    update_at TIMESTAMP(0) NOT NULL
);